name: cd-flyio

on:
  push:
    tags:
      - 'v*'      # ينشر عند عمل Tag مثل v1.0.0
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # إعداد flyctl
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          # لو عندك ملف fly.toml في الجذر، يكفي:
          flyctl deploy --remote-only
