name: php-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  quality-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, phpunit

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Lint (PHPCS)
        run: composer run lint

      - name: Static analysis (PHPStan)
        run: composer run stan

      - name: Unit tests (PHPUnit)
        run: composer run test
